Implements proper parsing for the as return type syntax (NOT analyze support)
SpaceManiac/SpacemanDMM pull request #370
Opened 2023-10-05 21:36 UTC by LemonInTheDark

I'm not hooking it into the existing return type system because I'm pretty sure it doesn't already support primitives, and I am not prepared to deal with that bullshit.

It will parse without erroring tho, so that's based

2023-10-17 07:33 UTC, SpaceManiac requested changes

2023-10-17 07:33 UTC, SpaceManiac commented on crates/dreammaker/src/parser.rs
> +        let Ok(ok_token) = next_token else {
ditto, possibly more below

2023-10-18 00:00 UTC, LemonInTheDark commented on crates/dreammaker/src/parser.rs
> +        if let Ok(None) = self.exact_ident("as") {
Sure. Refactored the function to use the result pattern, lemme know I got it right

2023-10-18 00:01 UTC, LemonInTheDark commented on crates/dreammaker/src/parser.rs
> +        let Ok(ok_token) = next_token else {
handled

2023-10-18 00:28 UTC, SpaceManiac commented on crates/dreammaker/src/parser.rs
> +        if let Ok(None) = self.exact_ident("as") {
Looks OK. New conflicts

2023-10-18 00:49 UTC, LemonInTheDark commented on crates/dreammaker/src/parser.rs
> +        if let Ok(None) = self.exact_ident("as") {
Copy that

2023-10-20 00:54 UTC, SpaceManiac approved these changes

2023-10-20 00:55 UTC, merged